# Generated by Django 3.1.7 on 2021-04-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfeatures',
            options={'verbose_name': 'Характеристика товара', 'verbose_name_plural': 'Характеристики товара'},
        ),
    ]
