# Generated by Django 3.1.7 on 2021-04-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0002_auto_20210413_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryfeature',
            options={'verbose_name': 'Категория характеристики', 'verbose_name_plural': 'Категории характеристик'},
        ),
    ]
