# Generated by Django 3.1.7 on 2021-05-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0003_auto_20210416_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurevalidator',
            options={'verbose_name': 'Валидатор значений харатеристик', 'verbose_name_plural': 'Валидатор значений харатеристики'},
        ),
    ]
