# Generated by Django 3.1.7 on 2021-03-08 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение товара')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Размер экрана')),
                ('display_type', models.CharField(max_length=255, verbose_name='Тип дисплея')),
                ('resolution', models.CharField(max_length=255, verbose_name='Разрешение экрана')),
                ('battery_capacity', models.CharField(max_length=255, verbose_name='Ёмкость аккумулятора')),
                ('ram', models.CharField(max_length=255, verbose_name='Объём памяти')),
                ('sd', models.BooleanField(default=True)),
                ('sd_capacity', models.CharField(max_length=255, verbose_name='Максимальный объем встраиваемой памяти')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Основная камера')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='Фронтальная камера')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.category', verbose_name='Категория товара')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Navigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение товара')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('resolution', models.CharField(max_length=255, verbose_name='Разрешение экрана')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Размер экрана')),
                ('display_type', models.CharField(max_length=255, verbose_name='Тип дисплея')),
                ('os', models.CharField(max_length=255, verbose_name='Операционная система')),
                ('ram', models.CharField(max_length=255, verbose_name='Объём памяти')),
                ('navsoftware', models.CharField(max_length=255, null=True, verbose_name='Навигационное ПО')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Страна производитель')),
                ('time_without_charge', models.CharField(max_length=255, verbose_name='Время работы от аккумулятора')),
                ('battery_capacity', models.CharField(max_length=255, verbose_name='Ёмкость аккумулятора')),
                ('weight', models.CharField(max_length=255, verbose_name='Вес')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.category', verbose_name='Категория товара')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
