# Generated by Django 3.1.7 on 2021-04-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0003_auto_20210416_1803'),
        ('MainApp', '0019_auto_20210416_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='features_for_product', to='specs.ProductFeatures', verbose_name='Характеристики'),
        ),
    ]
